/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelAndView;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BasicErrorControllerApi
 */
@Ignore
public class BasicErrorControllerApiTest {

    private final BasicErrorControllerApi api = new BasicErrorControllerApi();

    
    /**
     * errorHtml
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorHtmlUsingDELETETest() throws ApiException {
        ModelAndView response = api.errorHtmlUsingDELETE();

        // TODO: test validations
    }
    
    /**
     * errorHtml
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorHtmlUsingGETTest() throws ApiException {
        ModelAndView response = api.errorHtmlUsingGET();

        // TODO: test validations
    }
    
    /**
     * errorHtml
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorHtmlUsingHEADTest() throws ApiException {
        ModelAndView response = api.errorHtmlUsingHEAD();

        // TODO: test validations
    }
    
    /**
     * errorHtml
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorHtmlUsingOPTIONSTest() throws ApiException {
        ModelAndView response = api.errorHtmlUsingOPTIONS();

        // TODO: test validations
    }
    
    /**
     * errorHtml
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorHtmlUsingPATCHTest() throws ApiException {
        ModelAndView response = api.errorHtmlUsingPATCH();

        // TODO: test validations
    }
    
    /**
     * errorHtml
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorHtmlUsingPOSTTest() throws ApiException {
        ModelAndView response = api.errorHtmlUsingPOST();

        // TODO: test validations
    }
    
    /**
     * errorHtml
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorHtmlUsingPUTTest() throws ApiException {
        ModelAndView response = api.errorHtmlUsingPUT();

        // TODO: test validations
    }
    
}
