/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.PaymentDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentControllerApi
 */
@Ignore
public class PaymentControllerApiTest {

    private final PaymentControllerApi api = new PaymentControllerApi();

    
    /**
     * addUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addUserUsingPOSTTest() throws ApiException {
        PaymentDTO payment = null;
        PaymentDTO response = api.addUserUsingPOST(payment);

        // TODO: test validations
    }
    
    /**
     * findById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findByIdUsingGETTest() throws ApiException {
        String id = null;
        PaymentDTO response = api.findByIdUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUsingPOSTTest() throws ApiException {
        PaymentDTO payment = null;
        PaymentDTO response = api.updateUsingPOST(payment);

        // TODO: test validations
    }
    
}
